module.exports = [
    {
        city: "Brussels",
        latitude: 50.8333,
        longitude: 4.3333,
        country: "Belgium",
    },
    {
        city: "Paris",
        latitude: 48.8566,
        longitude: 2.3522,
        country: "France",
    },
    {
        city: "Toulouse",
        latitude: 43.6045,
        longitude: 1.4440,
        country: "France",
    },
    {
        city: "Nice",
        latitude: 43.7034,
        longitude: 7.2663,
        country: "France",
    },
    {
        city: "Brest",
        latitude: 48.3900,
        longitude: -4.4900,
        country: "France",
    },
    {
        city: "Grenoble",
        latitude: 45.1715,
        longitude: 5.7224,
        country: "France",
    },
    {
        city: "Clermont-Ferrand",
        latitude: 45.7831,
        longitude: 3.0824,
        country: "France",
    },
    {
        city: "Madrid",
        latitude: 40.4167,
        longitude: -3.7167,
        country: "Spain",
    },
    {
        city: "Barcelona",
        latitude: 41.3825,
        longitude: 2.1769,
        country: "Spain",
    },
    {
        city: "Sevilla",
        latitude: 37.3900,
        longitude: -5.9900,
        country: "Spain",
    },
    {
        city: "Granada",
        latitude: 37.1781,
        longitude: -3.6008,
        country: "Spain",
    },
    {
        city: "Santiago de Compostela",
        latitude: 42.8778,
        longitude: -8.5444,
        country: "Spain",
    },
    {
        city: "Hamburg",
        latitude: 53.5500,
        longitude: 10.0000,
        country: "Germany",
    },
    {
        city: "Munich",
        latitude: 48.1372,
        longitude: 11.5755,
        country: "Germany",
    },
    {
        city: "Hannover",
        latitude: 52.3744,
        longitude: 9.7386,
        country: "Germany",
    },
    {
        city: "Duisburg",
        latitude: 51.4322,
        longitude: 6.7611,
        country: "Germany",
    },
    {
        city: "Flensburg",
        latitude: 54.7819,
        longitude: 9.4367,
        country: "Germany",
    },
    {
        city: "Rome",
        latitude: 41.8931,
        longitude: 12.4828,
        country: "Italy",
    },
    {
        city: "Bari",
        latitude: 41.1253,
        longitude: 16.8667,
        country: "Italy",
    },
    {
        city: "Milan",
        latitude: 45.4669,
        longitude: 9.1900,
        country: "Italy",
    },
    {
        city: "Florence",
        latitude: 43.7714,
        longitude: 11.2542,
        country: "Italy",
    },
    {
        city: "Palermo",
        latitude: 38.1157,
        longitude: 13.3613,
        country: "Italy",
    },
    {
        city: "Lisbon",
        latitude: 38.7452,
        longitude: -9.1604,
        country: "Portugal",
    },
    {
        city: "Porto",
        latitude: 41.1495,
        longitude: -8.6108,
        country: "Portugal",
    },
    {
        city: "London",
        latitude: 51.5072,
        longitude: -0.1275,
        country: "England",
    },
    {
        city: "Newcastle",
        latitude: 55.0077,
        longitude: -1.6578,
        country: "England",
    },
    {
        city: "Plymouth",
        latitude: 50.3714,
        longitude: -4.1422,
        country: "England",
    },
    {
        city: "Sheffield",
        latitude: 53.3833,
        longitude: -1.4667,
        country: "England",
    },
    {
        city: "Edinburgh",
        latitude: 55.9530,
        longitude: -3.1890,
        country: "Scotland",
    },
    {
        city: "Cardiff",
        latitude: 51.4833,
        longitude: -3.1833,
        country: "Wales",
    },
    {
        city: "Belfast",
        latitude: 54.5964,
        longitude: -5.9300,
        country: "Northern Ireland",
    },
    {
        city: "Cork",
        latitude: 51.9000,
        longitude: -8.4731,
        country: "Ireland",
    },
    {
        city: "Dublin",
        latitude: 53.3497,
        longitude: -6.2603,
        country: "Ireland",
    },
    {
        city: "Zürich",
        latitude: 47.3786,
        longitude: 8.5400,
        country: "Switzerland",
    },
    {
        city: "Amsterdam",
        latitude: 52.3667,
        longitude: 4.8833,
        country: "Netherlands",
    },
    {
        city: "Copenhagen",
        latitude: 55.6761,
        longitude: 12.5689,
        country: "Denmark",
    },
    {
        city: "Oslo",
        latitude: 59.9111,
        longitude: 10.7528,
        country: "Norway",
    },
    {
        city: "Bergen",
        latitude: 60.3925,
        longitude: 5.3233,
        country: "Norway",
    },
    {
        city: "Stockholm",
        latitude: 59.3294,
        longitude: 18.0686,
        country: "Sweden",
    },
    {
        city: "Prague",
        latitude: 50.0833,
        longitude: 14.4167,
        country: "Czechia",
    },
    {
        city: "Vienna",
        latitude: 48.2083,
        longitude: 16.3731,
        country: "Austria",
    },
    {
        city: "Ljubljana",
        latitude: 46.0500,
        longitude: 14.5167,
        country: "Slovenia",
    },
    {
        city: "Zagreb",
        latitude: 45.8000,
        longitude: 15.9500,
        country: "Croatia",
    },
    {
        city: "Warsaw",
        latitude: 52.2167,
        longitude: 21.0333,
        country: "Poland",
    },
    {
        city: "Gdańsk",
        latitude: 54.3667,
        longitude: 18.6333,
        country: "Poland",
    },
    {
        city: "Poznań",
        latitude: 52.4000,
        longitude: 16.9167,
        country: "Poland",
    },
    {
        city: "Bratislava",
        latitude: 48.1447,
        longitude: 17.1128,
        country: "Slovakia",
    },
    {
        city: "Budapest",
        latitude: 47.4983,
        longitude: 19.0408,
        country: "Hungary",
    },
    {
        city: "Belgrade",
        latitude: 44.8167,
        longitude: 20.4667,
        country: "Serbia",
    },
    {
        city: "Sarajevo",
        latitude: 43.8667,
        longitude: 18.4167,
        country: "Bosnia And Herzegovina",
    },
    {
        city: "Tirana",
        latitude: 41.3300,
        longitude: 19.8200,
        country: "Albania",
    },
    {
        city: "Athens",
        latitude: 37.9842,
        longitude: 23.7281,
        country: "Greece",
    },
    {
        city: "Thessaloníki",
        latitude: 40.6403,
        longitude: 22.9356,
        country: "Greece",
    },
    {
        city: "Pátra",
        latitude: 38.2500,
        longitude: 21.7333,
        country: "Greece",
    },
    {
        city: "Helsinki",
        latitude: 60.1756,
        longitude: 24.9342,
        country: "Finland",
    },
    {
        city: "Tallinn",
        latitude: 59.4372,
        longitude: 24.7450,
        country: "Estonia",
    },
    {
        city: "Riga",
        latitude: 56.9475,
        longitude: 24.1069,
        country: "Latvia",
    },
    {
        city: "Vilnius",
        latitude: 54.6833,
        longitude: 25.2833,
        country: "Lithuania",
    },
    {
        city: "Minsk",
        latitude: 53.9022,
        longitude: 27.5618,
        country: "Belarus",
    },
    {
        city: "Kyiv",
        latitude: 50.4500,
        longitude: 30.5236,
        country: "Ukraine",
    },
    {
        city: "Odesa",
        latitude: 46.4775,
        longitude: 30.7326,
        country: "Ukraine",
    },
    {
        city: "Lviv",
        latitude: 49.8419,
        longitude: 24.0315,
        country: "Ukraine",
    },
    {
        city: "Chisinau",
        latitude: 47.0228,
        longitude: 28.8353,
        country: "Moldova",
    },
    {
        city: "Bucharest",
        latitude: 44.4000,
        longitude: 26.0833,
        country: "Romania",
    },
    {
        city: "Cluj-Napoca",
        latitude: 46.7667,
        longitude: 23.6000,
        country: "Romania",
    },
    {
        city: "Sofia",
        latitude: 42.6979,
        longitude: 23.3217,
        country: "Bulgaria",
    },
    {
        city: "Varna",
        latitude: 43.2114,
        longitude: 27.9111,
        country: "Bulgaria",
    },
    {
        city: "Istanbul",
        latitude: 41.0100,
        longitude: 28.9603,
        country: "Turkey",
    },
    {
        city: "Sassari",
        latitude: 40.7267,
        longitude: 8.5592,
        country: "Italy",
    },
]
